### ISSUE TITLE
Formulas in docs not rendered properly 

### ISSUE THREAD

**Issue by Ghost-VR** [fy-meng/position-based-fluid#1]
position-based-fluid/docs/index.md
![image](https://user-images.githubusercontent.com/12619799/58976374-eba2d880-878c-11e9-86cc-82fcdeb491e4.png)

o.O

**Comment by fy-meng** [comment]
GitHub-flavored Markdown currently does not support LaTeX formulas, so we have to use a MathJax script with Jekyll to render them. Please checkout our GitHub Page instead of the standard rendered .md.
